# localization packages
arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/gen
untranslated-messages-file: lib/gen/untranslated_messages.json
nullable-getter: false
